# Generated by Django 3.1.7 on 2021-04-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=225, verbose_name='Title')),
                ('about', models.TextField(max_length=5000, verbose_name='About')),
                ('image', models.ImageField(upload_to='media/About_app/image', verbose_name='Image')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutExcutives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=225, verbose_name='Name')),
                ('office', models.TextField(max_length=225, verbose_name='Office')),
                ('about', models.TextField(max_length=5000, verbose_name='About')),
                ('image', models.ImageField(upload_to='media/About_Excutives/image', verbose_name='Image')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
