# Generated by Django 3.1.7 on 2021-09-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_likepaymentunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepaymentunit',
            name='likeId',
            field=models.IntegerField(default=1),
        ),
    ]
