# Generated by Django 3.1.7 on 2021-09-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_likepaymentunit_likeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepaymentunit',
            name='payment_threshold',
            field=models.BigIntegerField(default=1000),
        ),
    ]
