# Generated by Django 3.1.7 on 2021-12-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_likepaymentunit_payment_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepaymentunit',
            name='unit',
            field=models.FloatField(default=1),
        ),
    ]
