# Generated by Django 3.1.7 on 2021-03-08 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_image', models.FileField(upload_to='media/Donewithit', verbose_name='First image')),
                ('second_image', models.FileField(blank=True, null=True, upload_to='media/Donewithit', verbose_name='Second image')),
                ('third_image', models.FileField(blank=True, null=True, upload_to='media/Donewithit', verbose_name='Third image')),
                ('item_name', models.CharField(max_length=20, verbose_name='Item Name')),
                ('item_dis', models.CharField(blank=True, max_length=225, null=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('Book', 'Book'), ('Phone', 'Phone'), ('Computer', 'Computer'), ('Appliances', 'Appliances'), ('Gadget', 'Gadget'), ('Furniture', 'Furniture'), ('Apartment', 'Apartment'), ('Clothing', 'Clothing'), ('Vehicle', 'Vehicle'), ('Kitchen', 'Kitchen'), ('Others', 'Others')], default='Book', max_length=150)),
                ('location', models.CharField(blank=True, max_length=225, null=True, verbose_name='location')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Price')),
                ('sold', models.BooleanField(default=False)),
                ('free', models.BooleanField(default=False, verbose_name='Give item for free')),
                ('negotiable', models.BooleanField(default=True, verbose_name='Negotiable')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
