# Generated by Django 3.1.7 on 2021-03-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoneWithIt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='second_image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='third_image',
        ),
        migrations.AddField(
            model_name='item',
            name='contact',
            field=models.BooleanField(default=False, verbose_name='Give item for free'),
        ),
        migrations.AlterField(
            model_name='item',
            name='first_image',
            field=models.FileField(upload_to='media/Donewithit', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='free',
            field=models.BooleanField(default=False, verbose_name='Contact for price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_dis',
            field=models.TextField(blank=True, max_length=225, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=100, verbose_name='Item Name'),
        ),
    ]
