# Generated by Django 3.1.7 on 2021-04-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostsManagement', '0002_post_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
