# Generated by Django 3.1.7 on 2021-12-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostsManagement', '0003_remove_post_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='media/Post_thumbnail', verbose_name='Post Thumbnail')),
            ],
        ),
    ]
