# Generated by Django 3.1.7 on 2021-03-13 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Userprofile', '0002_auto_20210227_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Account number')),
                ('account_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Account name')),
                ('bank', models.CharField(blank=True, max_length=30, null=True, verbose_name='Bank')),
                ('paid', models.BigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
