# Generated by Django 3.1.7 on 2021-03-14 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Userprofile', '0004_auto_20210314_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='account_name',
            field=models.CharField(default='account name', max_length=100, verbose_name='Account name'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='account_number',
            field=models.CharField(default='account number', max_length=20, verbose_name='Account number'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='bank',
            field=models.CharField(default='bank', max_length=30, verbose_name='Bank'),
        ),
        migrations.CreateModel(
            name='RequestPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.BigIntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='Userprofile.paymentdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raccount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
