# Generated by Django 3.1.7 on 2021-03-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0005_auto_20210314_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestpayment',
            name='payment_details',
        ),
    ]
