# Generated by Django 3.1.7 on 2021-12-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0009_trending_trend_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_image', verbose_name='Profile Image'),
        ),
    ]
